"""add last otp sent at

Revision ID: d9274ab1c913
Revises: 3cd33fe51ea6
Create Date: 2026-06-15 23:59:43.580575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9274ab1c913'
down_revision: Union[str, Sequence[str], None] = '3cd33fe51ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp_sent_at')
    # ### end Alembic commands ###
